---
- name: GET_and_POST
  hosts: vehicle.idir.bcgov
  gather_facts: false
  any_errors_fatal: true
  vars:
    your_api_endpoint: "http://nagios.im.gov.bc.ca/nrdp/"
    your_incoming_webhook: "http://nagios.im.gov.bc.ca/nrdp/"
    your_token: "mPsNf7ANZfgW"
  
  tasks:
  - name: Perform API GET to return the status of remote service
    win_shell: mkdir e:\tmppaul
    uri:
      url: "{{ your_api_endpoint }}"
     
    
 
