---
- name: GET_and_POST
  hosts: vehicle.idir.bcgov
  gather_facts: false
  any_errors_fatal: true
  vars:
    your_api_endpoint: "http://nagios.im.gov.bc.ca/nrdp/"
    your_incoming_webhook: "http://nagios.im.gov.bc.ca/nrdp/"
    your_token: "S2EBPf7CS4dq8s8vo4YIu7Bv0vfMGeWCTdBigS46Xb7r2UjimdCMKjKrIhZV7RlR"
  
 
     
    
 
