- name: Send NRDP check results
  hosts: vehicle.idir.bcgov
  gather_facts: false

  vars:
    nrdp_url: "http://nagios.im.gov.bc.ca/nrdp/"
    nrdp_token: "mPsNf7ANZfgW"

    nrdp_json:
      checkresults:
        - checkresult:
            type: host
          hostname: somehost
          state: "0"
          output: "Everything looks okay! | perfdata=1;"

        - checkresult:
            type: service
          hostname: somehost
          servicename: someservice
          state: "1"
          output: "WARNING: Danger Will Robinson! | perfdata=1;"

  tasks:

    - name: Submit NRDP check results
      uri:
        url: "{{ nrdp_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          cmd: submitcheck
          token: "{{ nrdp_token }}"
          json: "{{ nrdp_json | to_json }}"
        validate_certs: false
        return_content: true
      register: nrdp_result

    - debug:
        var: nrdp_result.content