---
- name: GET_and_POST
  hosts: vehicle.idir.bcgov
  gather_facts: false
  any_errors_fatal: true
  vars:
    your_api_endpoint: "http://nagios.im.gov.bc.ca/nrdp/"
    your_incoming_webhook: "http://nagios.im.gov.bc.ca/nrdp/"
    your_token: "mPsNf7ANZfgW"
  
 
     
    
 
