---
- name: GET_and_POST
  hosts: vehicle.idir.bcgov
  gather_facts: false
  any_errors_fatal: true
  vars:
    your_api_endpoint: "http://nagios.im.gov.bc.ca/nrdp/"
    your_incoming_webhook: "http://nagios.im.gov.bc.ca/nrdp/"
    your_token: "mPsNf7ANZfgW"
  
  tasks:
  - name: Perform API GET to return the status of remote service
    uri:
      url: "{{ your_api_endpoint }}"
      method: GET
      return_content: yes
      body_format: json
      status_code: 200
      headers:
        Authorization: "Bearer {{ your_token }}"
    register: results_of_get
    
    
  - name: Read the return data and POST to webhook if anything other than Opeartional is found in Status
    uri:
      url: "{{ your_incoming_webhook }}"
      method: POST
      return_content: yes
      body: '{"@checkresults":""@checkresult"","@type":"service","hostname":"ansible","servicename":"ansible","state":"1","output":"WARNING Danger Will Robinson"}'
      body_format: json
   
