---
- hosts: vehicle.idir.bcgov

  tasks: 
 
   - name: Check my username
     ansible.windows.win_whoami:
     become: true
     
   - name: Run ps1 ver 1
     win_shell: |
          $value = Test-Path -Path e:\temp
          if ($value) {
              New-Item e:\temp\test.txt -ItemType File
          }
     
