---
- hosts: vehicle.idir.bcgov

  tasks: 
  - name: Save the result of 'whoami' in 'whoami_out'
    ansible.windows.win_command: whoami
    register: whoami_out
    
  - name: command output
    ansible.builtin.debug:
