---
- hosts: vehicle.idir.bcgov

  tasks: 
    
   - debug: var=username_on_the_host

   - name: Run whoami without become.
     command: whoami
     changed_when: false
     become: false
     register: whoami
   
   - name: find whoami based on credentials supplied
     win_whoami:
     register: whoami_base

   - name: output base user
     debug:
       msg: "{{ whoami_base.account.account_name }}"
       
   - name: Return all entries within the groups organizational unit.
     community.general.ldap_search:
     dn: "ou=VPN Groups,ou=Citizens Services,dc=idir.bcgov,dc=bcgov"
     register: ldap_groups
