---
- hosts: panga.idir.bcgov

  tasks: 
  - name: Run remote PowerShell Script
    win_command: powershell.exe -ExecutionPolicy ByPass -File E:/Tidal/AD_Contacts_Export/CbreExpAnsible.ps1
      
     
