---
- hosts: panga.idir.bcgov

  tasks: 
  - name: Run remote PowerShell Script
    win_shell: powershell.exe -ExecutionPolicy ByPass -File E:/Tidal/Futureofwork/futureofworktransfer.ps1
    register: command_output
