---
- hosts: vehicle.idir.bcgov

  tasks: 
    
   - debug: var=username_on_the_host
   
   - name: win command
     win_command: whomai /all
     become: yes
     become_method: runas
     vars:
      ansible_become_user: '{{ ansible_user }}'
      ansible_become_pass: '{{ ansible_password }}'
   
   - name: find whoami based on credentials supplied
     command: win_whoami
     become: true
     register: whoami_base

   - name: find whoami based on become
     command: win_whoami
     become: true
     become_user: administrator
     register: whoami_base


   - name: output base user
     debug:
       msg: "{{ whoami_base.account.account_name }}"
       
  
