---
  - hosts: guppy.bcgov
 
    tasks:
     - name: List contents of 
       ansible.builtin.find:
         paths: /
         file_type: file
         patterns: '*'
         recurse: no
       
     
